### ISSUE TITLE
Render mermaid diagrams?

### ISSUE THREAD

**Issue by caro401** [caro401/notes#6]
https://github.com/withastro/astro/issues/4433
https://github.com/JuanM04/portfolio/blob/main/src/content/docs/with-markiplier/chica.md

**Comment by stereobooster** [comment]
Maybe this can be useful https://astro-digital-garden.stereobooster.com/recipes/mermaid-diagrams-in-markdown/

**Comment by caro401** [comment]
Handled automatically now by [`starlight-obsidian` plugin](https://starlight-obsidian.vercel.app/guides/features/#advanced-formatting-syntax)
